-- ============================================================
-- Admin backend schema
-- Run once in Supabase SQL editor
-- ============================================================

-- Admin users — separate from public pothole reporters.
-- Accounts are inactive until activated via invite link.
create table if not exists admin_users (
  id              uuid primary key default gen_random_uuid(),
  email           text not null unique,
  password_hash   text not null,       -- PBKDF2-SHA-256: "iterations:salt_hex:hash_hex"
  first_name      text not null,
  last_name       text not null,
  role            text not null default 'editor'
                  check (role in ('admin', 'editor', 'viewer')),
  is_active       boolean not null default false,
  activated_at    timestamptz,
  last_login_at   timestamptz,
  totp_enabled    boolean not null default false,
  totp_secret     text,               -- AES-GCM encrypted base32 secret ("iv_hex:ciphertext_hex")
  backup_codes    text,               -- JSON array of PBKDF2-hashed single-use recovery codes
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now()
);

-- Sessions (opaque token, idle + absolute timeouts enforced in application layer)
create table if not exists admin_sessions (
  id               text primary key,   -- cryptographically random, generated by application
  user_id          uuid not null references admin_users(id) on delete cascade,
  expires_at       timestamptz not null,
  created_at       timestamptz not null default now(),
  last_activity_at timestamptz not null default now(),
  ip_address       text,
  user_agent       text
);

create index if not exists admin_sessions_user_idx    on admin_sessions (user_id);
create index if not exists admin_sessions_expires_idx on admin_sessions (expires_at);

-- Invite codes (single-use; role comes from invite, never from request body)
create table if not exists admin_invite_codes (
  id          uuid primary key default gen_random_uuid(),
  code        text not null unique,
  email       text,                       -- null = anyone can use; non-null = email-restricted
  role        text not null default 'editor'
              check (role in ('admin', 'editor', 'viewer')),
  created_by  uuid references admin_users(id) on delete set null,
  used_by     uuid references admin_users(id) on delete set null,
  created_at  timestamptz not null default now(),
  expires_at  timestamptz not null,
  used_at     timestamptz,
  is_active   boolean not null default true
);

create index if not exists admin_invite_codes_code_idx on admin_invite_codes (code);

-- Short-lived MFA challenges (5-minute window; atomically marked used to prevent replay)
create table if not exists admin_mfa_challenges (
  id          uuid primary key default gen_random_uuid(),
  token       text not null unique,
  user_id     uuid not null references admin_users(id) on delete cascade,
  ip_address  text,
  user_agent  text,
  expires_at  timestamptz not null,
  used        boolean not null default false,
  used_at     timestamptz,
  created_at  timestamptz not null default now()
);

create index if not exists admin_mfa_challenges_user_idx    on admin_mfa_challenges (user_id);
create index if not exists admin_mfa_challenges_expires_idx on admin_mfa_challenges (expires_at);

-- Trusted devices — skip MFA for 30 days on known browsers
create table if not exists admin_trusted_devices (
  id           uuid primary key default gen_random_uuid(),
  token        text not null unique,
  user_id      uuid not null references admin_users(id) on delete cascade,
  ip_address   text,
  user_agent   text,
  created_at   timestamptz not null default now(),
  last_used_at timestamptz not null default now(),
  expires_at   timestamptz not null
);

create index if not exists admin_trusted_devices_user_idx    on admin_trusted_devices (user_id);
create index if not exists admin_trusted_devices_expires_idx on admin_trusted_devices (expires_at);

-- Auth attempt log — used for DB-backed rate limiting (5 failures / 10 min per email+IP)
create table if not exists admin_auth_attempts (
  id             uuid primary key default gen_random_uuid(),
  user_id        uuid references admin_users(id) on delete set null,
  email          text,
  ip_address     text,
  user_agent     text,
  attempt_type   text not null check (attempt_type in ('login', 'mfa', 'signup')),
  success        boolean not null,
  failure_reason text,
  created_at     timestamptz not null default now()
);

create index if not exists admin_auth_attempts_email_ip_idx
  on admin_auth_attempts (email, ip_address, created_at desc);
create index if not exists admin_auth_attempts_user_idx
  on admin_auth_attempts (user_id, created_at desc);

-- Audit log — every state-changing admin action
create table if not exists admin_audit_log (
  id            uuid primary key default gen_random_uuid(),
  user_id       uuid references admin_users(id) on delete set null,
  action        text not null,       -- e.g. 'photo.approve', 'pothole.delete', 'user.deactivate'
  resource_type text,                -- 'photo' | 'pothole' | 'user' | 'invite'
  resource_id   text,                -- UUID of affected record
  details       jsonb,               -- before/after values, notes
  ip_address    text,
  created_at    timestamptz not null default now()
);

create index if not exists admin_audit_log_user_idx     on admin_audit_log (user_id, created_at desc);
create index if not exists admin_audit_log_resource_idx on admin_audit_log (resource_type, resource_id);
create index if not exists admin_audit_log_created_idx  on admin_audit_log (created_at desc);

-- Admin-initiated password reset tokens (24h expiry; 1 active at a time per user)
create table if not exists admin_password_resets (
  id         uuid primary key default gen_random_uuid(),
  user_id    uuid not null references admin_users(id) on delete cascade,
  token      text not null unique,
  created_by uuid references admin_users(id) on delete set null,
  expires_at timestamptz not null,
  used       boolean not null default false,
  used_at    timestamptz,
  created_at timestamptz not null default now()
);

create index if not exists admin_password_resets_user_idx  on admin_password_resets (user_id);
create index if not exists admin_password_resets_token_idx on admin_password_resets (token);

-- RLS: all admin tables accessed via service role only — no public policies
alter table admin_users            enable row level security;
alter table admin_sessions         enable row level security;
alter table admin_invite_codes     enable row level security;
alter table admin_mfa_challenges   enable row level security;
alter table admin_trusted_devices  enable row level security;
alter table admin_auth_attempts    enable row level security;
alter table admin_audit_log        enable row level security;
alter table admin_password_resets  enable row level security;

-- ============================================================
-- Bootstrap: create the first admin invite (run once manually)
-- ============================================================
-- INSERT INTO admin_invite_codes (code, role, expires_at)
-- VALUES (gen_random_uuid()::text, 'admin', now() + interval '1 day');
-- Copy the code value and visit /admin/auth/signup?invite=<code>
